### PR TITLE
Converts to java

### PR DESCRIPTION
**Pull request by midaslefkowitz**
I decided to remove butterknife since there were only two findViewByID's and it was causing dependency conflict issues

### CODE REVIEW

**Comment by saket** [comment]
Sorry if I wasn't clear enough, but I'm not in favor of going backwards and converting this project to java. I'll simply direct users to your fork who don't want to add kotlin yet. For e.g., issue #4. 

Thanks for doing this!

**Comment by midaslefkowitz** [comment]
No need to "go backwards" you can just keep a Java branch on your
project... there would be master and Java.

I don't mind keeping it as a fork, I just think it's cleaner to keep the
project in one place. Whatever you decide.

**Comment by saket** [comment]
> you can just keep a Java branch on your project there would be master and Java

That would be better, but you raised a PR to merge this into master instead of a separate branch :)

**Comment by saket** [comment]
Keeping two branches also means that I'll have to remember to update both when making any fixes, which is not very ideal. It's just easier to let the community help me with this.

**Pull request closed without merging**
